version: '3.8'

services:
  app-java:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db-mysql
    environment:
      # Sửa "demo_docker_db" thành tên Database ứng dụng của bạn nhé
      SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/demo_docker_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      # Tự động tạo bảng dựa trên entity
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect

  db-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo_docker_db # Phải khớp với URL ở phần app-java
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
